
#Load necessary packages.
library(shiny)
library(EBImage)
library(jpeg)
library(magick)
library(ggplot2)
library(writexl)
library(shinydashboard)
library(dplyr)
library(tibble)
library(ComplexHeatmap)
library(grid)
library(gridExtra)
library(cowplot)
library(DT)
library(waiter)
library(viridis)
library(shinycssloaders)
library(plotly)

#Function that creates the user interface for the site setup.
site_setup <- function(){
  ui <- 
    #Create the Dashboard Header that includes all of the tabs on the left-side of the website and their respective sub-tabs.     
    dashboardPage(skin = "black",
                  dashboardHeader(title = "Axon-o-matic", titleWidth = 187),
                  dashboardSidebar(width = 250,
                    sidebarMenu(
                      menuItem("Home", tabName = 'Home', icon = icon('home', lib='font-awesome')),
                      menuItem("Axon Quantification", tabName = 'Axon_Counting', icon = icon('water', lib='font-awesome'),
                               menuSubItem("Absolute # of Axons", tabName = 'CTB_Only', icon = icon('water', lib='font-awesome')),
                               menuSubItem("Normalized # of Axons", tabName = 'CTB_DAPI', icon = icon('water', lib='font-awesome')),
                               menuSubItem("Multiple Files (Absolute # of Axons)", tabName = 'Multiple_Files', icon = icon('water', lib='font-awesome'))),
                      menuItem("MFI Quantification", tabName = 'MFI_Quantification', icon = icon('lightbulb', lib='font-awesome'),
                               menuSubItem("Absolute # MFI", tabName = 'SCG10_Only', icon = icon('lightbulb', lib='font-awesome')),
                               menuSubItem("Normalized MFI", tabName = 'SCG10_DAPI', icon = icon('lightbulb', lib='font-awesome')),
                               menuSubItem("Multiple Files (Absolute # MFI)", tabName = "multiple_mfi", icon = icon('lightbulb', lib='font-awesome'))),
                      menuItem("RGC Quantification", tabName = 'Rbpms_Quant', icon = icon('circle', lib='font-awesome'),
                               menuSubItem("Single File", tabName = 'Rbpms_Counting', icon = icon('circle', lib='font-awesome')),
                               menuSubItem(" Multiple Files", tabName = 'Rbpms_multiple_files', icon = icon('circle', lib='font-awesome'))
                      ))),

                  #Create the user interface for each tab item, and what is displayed on each tab.                  
                  dashboardBody(
                    tabItems(
                  #Home tab that includes the RMarkdown file to display as the homepage.     
                      tabItem(tabName = 'Home',
                              fluidPage(
                                includeMarkdown('Intro_1.md'))),
                  #Total Axon Quantification Tab User Interface
                       tabItem(tabName = 'CTB_Only',
                              fluidPage(
                                h2("Total Axon Quantification"),
                                br(),
                                h4("Image Pre-Processing Instructions"),
                                h6("1. Open FIJI Software, select File --> Open --> select image file."),
                                h6("2. To straighten & crop nerves from injury site to the distal nerve, do the following:"),
                                h6("   a. Select Edit --> Options --> Line Width, set equal to ~2,500"),
                                h6("   b. Right-click line tile --> Select segmented line"),
                                h6("   c. Click at nerve crush site, and then click in the middle of the nerve until at distal nerve end, then right-click."),
                                h6("   d. Search for the straighten plugin and then run."),
                                h6("3. Select Image --> Type --> 8-bit"),
                                h6("4. Select Image --> Adjust --> Brightness_Contrast, adjust to have signal similar to the example image on this page."),
                                h6("5. Select Image --> Scale --> Should be set to 50% (0.5) --> Select OK"),
                                h6("6. Select File --> Save as --> Tiff"),
                                h6("*Please note that high-quality images are needed for proper quantification (please see example below)."),
                                fluidRow(withSpinner(plotOutput("pdf_5"), type = 6), style = 'padding:4px;'),
                                br(),
                                h4("Image Analysis"),
                                h6("1. Upload tiff image file and wait for upload to complete."),
                                h6("2. Click the submit button to run the image analysis. Please allow a few minutes for image processing."),
                                h6("3. When finished, you may click the reset button to submit another image for analysis."),
                                h6("*Files may generally take ~30 seconds to process."),
                                br(),
                                fluidRow(column(6, fileInput("file1", "Please upload an 8-bit Tiff Image"), actionButton("submit", "Submit"))),
                                fluidRow(h4("Original Image"), withSpinner(plotOutput("img"), type = 6), style = 'padding:4px;'),
                                fluidRow(h4("Masked Image"), withSpinner(plotOutput("mask"), type = 6), style = 'padding:4px;'),
                                fluidRow(h4("Object Image"), withSpinner(plotOutput("obj"), type = 6), style = 'padding:4px;'),
                                fluidRow(h4("Interval Quantification"),column(3,h6("First Interval"), withSpinner(plotOutput("int_1"), type = 6), style = 'padding:4px;'), column(3,h6("Second Interval"), withSpinner(plotOutput("int_2"), type = 6),style = 'padding:4px;'), column(3,h6("Third Interval"), withSpinner(plotOutput("int_3"), type = 6), style = 'padding:4px;'), column(3,h6("Fourth Interval"), withSpinner(plotOutput("int_4"), type = 6)), style = 'padding4px;'),
                                h4("Number of Axons"),
                                fluidRow(withSpinner(DTOutput("results"), type = 6), style = 'padding:4px;', actionButton("reset", "Reset"))
                              )),
                  #Normalized Axon Quantification Tab User Interface
                      tabItem(tabName = 'CTB_DAPI',
                              fluidPage(
                                h2("Normalized Axon Quantification"),
                                br(),
                                h4("Image Pre-Processing Instructions"),
                                h6("1. Open FIJI Software, select File --> Open --> select image file."),
                                h6("2. To straighten & crop nerves from injury site to the distal nerve, do the following:"),
                                h6("   a. Select Edit --> Options --> Line Width, set equal to ~2,500"),
                                h6("   b. Right-click line tile --> Select segmented line"),
                                h6("   c. Click at nerve crush site, and then click in the middle of the nerve until at distal nerve end, then right-click."),
                                h6("   d. Search for the straighten plugin and then run."),
                                h6("3. Select Image --> Type --> 8-bit"),
                                h6("4. Select Image --> Adjust --> Brightness_Contrast, adjust to have signal similar to the example image on this page."),
                                h6("5. Select Image --> Scale --> Should be set to 50% (0.5) --> Select OK"),
                                h6("6. Select File --> Save as --> Tiff"),
                                h6("7. Record the pixel height in inches: Select Image --> Properties"),
                                h6("8. Repeat steps 1-5 with an image file of nuclear staining (i.e., DAPI)."),
                                h6("*Please note no nuclear staining can be on the edges of the cropped image or the code may fail to acquire the upper/lower limit of the nerve width."),
                                h6("*Please note that high-quality images are needed for proper quantification (please see example below)."),
                                h6("CTB Example"),
                                fluidRow(withSpinner(plotOutput("pdf_6"), type = 6), style = 'padding:4px;'),
                                h6("Hoechst Example"),
                                fluidRow(withSpinner(plotOutput("pdf_7"), type = 6), style = 'padding:4px;'),
                                br(),
                                h4("Image Analysis"),
                                h6("1. Upload tiff image file and wait for upload to complete."),
                                h6("2. Upload nuclear stained tiff image file and wait for upload to complete."),
                                h6("3. Input the height per pixel in inches for the image."),
                                h6("4. Click the submit button to run the image analysis. Please allow a few minutes for image processing."),
                                h6("5. When finished, you may click the reset button to submit another image for analysis."),
                                h6("*Files may generally need ~2 minutes of processing time."),
                                br(),
                                fluidRow(column(6, fileInput("file4", "Please upload an 8-bit Tiff image", multiple = TRUE))),
                                fluidRow(column(6, fileInput("file5", "Please upload an 8-bit Tiff image (nuclear staining)"))),
                                fluidRow(numericInput("mtpr", "Pixel Height (Inches)", value = 0, min = 0), actionButton("submit_4", "Submit")),
                                fluidRow(h4("Original Image"), column(6, h6("Axon Stain"),withSpinner(plotOutput("img_4"), type = 6)), column(6,h6("Nuclear Stain"), withSpinner(plotOutput("img_5"),type = 6)), style = 'padding:4px;'),
                                fluidRow(h4("Masked Image"), column(6, h6("Axon Stain"), withSpinner(plotOutput("mask_4"), type = 6)), column(6,h6("Nuclear Stain"), withSpinner(plotOutput("mask_5"), type = 6)), style = 'padding:4px;'),
                                fluidRow(h4("Object Image"), column(6, h6("Axon Stain"), withSpinner(plotOutput("obj_4"), type = 6)), column(6,h6("Nuclear Stain"), withSpinner(plotOutput('obj_5'), type = 6)), style = 'padding:4px;'),
                                fluidRow(h4("Interval Quantification"), column(3,h6("First Interval"), h6("Axon Stain"), withSpinner(plotOutput("int_1_4"), type = 6), h6("Nuclear Stain"), withSpinner(plotOutput("int_1_5"), type = 6)), column(3,h6("Second Interval"),h6("Axon Stain"),withSpinner(plotOutput("int_2_4"),type = 6), h6("Nuclear Stain"), withSpinner(plotOutput("int_2_5"), type = 6)), column(3,h6("Third Interval"),h6("Axon Stain"),withSpinner(plotOutput("int_3_4"), type = 6), h6("Nuclear Stain"),withSpinner(plotOutput("int_3_5"), type = 6)), column(3,h6("Fourth Interval"), h6("Axon Stain"),withSpinner(plotOutput("int_4_4"), type = 6), h6("Nuclear Stain"),withSpinner(plotOutput("int_4_5"), type = 6)), style = 'padding:4px;'),
                                h4("Number of Axons"),
                                fluidRow(withSpinner(DTOutput("results_4"), type = 6), style = 'padding:4px;', actionButton("reset_4", "Reset"))
                              )),
                  #Multiple Files Total Axon Quantification Tab User Interface    
                  tabItem(tabName = "Multiple_Files",
                              fluidPage(shinyjs::useShinyjs(),
                                        h2("Axon Quantification for Multiple Files"),
                                        br(),
                                        h4("Image Pre-Processing Instructions (to do for each file)"),
                                        h6("1. Open FIJI Software, select File --> Open --> select image file."),
                                        h6("2. To straighten & crop nerves from injury site to the distal nerve, do the following:"),
                                        h6("   a. Select Edit --> Options --> Line Width, set equal to ~2,500"),
                                        h6("   b. Right-click line tile --> Select segmented line"),
                                        h6("   c. Click at nerve crush site, and then click in the middle of the nerve until at distal nerve end, then right-click."),
                                        h6("   d. Search for the straighten plugin and then run."),
                                        h6("3. Select Image --> Type --> 8-bit"),
                                        h6("4. Select Image --> Adjust --> Brightness_Contrast, adjust to have signal similar to the example image on this page."),
                                        h6("5. Select Image --> Scale --> Should be set to 50% (0.5) --> Select OK"),
                                        h6("6. Select File --> Save as --> Tiff"),
                                        h6("*Please note that high-quality images are needed for proper quantification (please see example below)."),
                                        fluidRow(withSpinner(plotOutput("pdf_8"), type = 6), style = 'padding:4px;'),
                                        br(),
                                        h4("Image Analysis"),
                                        h6("1. Upload your tiff image files and wait for upload to complete. Please upload image files (select multiple files at once, we recommend no more than 10 at a time) instead of a folder of files."),
                                        h6("2. Click the submit button to run the image analysis. Please allow a few minutes for image processing."),
                                        h6("*One file may generally take 1-2 minutes to process, so please be patient for the program to finish all files."),
                                        br(),  
                                        fluidRow(column(6, fileInput("list_multiple_files_axon_quantification", "Please upload your images.", multiple = TRUE, accept = c(".tif", ".tiff", "image/tiff")), actionButton("submit_multiple_files", "Submit"))),
                                        h4("Number of Axons"),
                                        fluidRow(withSpinner(DTOutput("results_multiple_files"), type = 6), style = 'padding:4px;'),
                                        h6("*If submitting more than one job for batch processing, please upload the next batch of images to process once the original batch finishes and hit submit again."),
                              )),
                  #Total MFI Tab User Interface
                      tabItem(tabName = 'SCG10_Only',
                              fluidPage(
                                h2("Total Mean Fluorescence Intensity (MFI) Quantification"),
                                br(),
                                h4("Image Pre-Processing Instructions"),
                                h6("1. Open FIJI Software, select File --> Open --> select image file."),
                                h6("2. To straighten & crop nerves from injury site to the distal nerve, do the following:"),
                                h6("   a. Select Edit --> Options --> Line Width, set equal to ~2,500"),
                                h6("      *For MFI quantification, it is important that this number is optimized to fit the nerve and reduce background image that may dilute the overall MFI quantification."),
                                h6("   b. Right-click line tile --> Select segmented line"),
                                h6("   c. Click at nerve crush site, and then click in the middle of the nerve until at distal nerve end, then right-click."),
                                h6("   d. Search for the straighten plugin and then run."),
                                h6("   *Make sure empty space is not present in the cropped image, or this will interfere with the MFI calculation."),
                                h6("3. Select Image --> Type --> 8-bit"),
                                h6("4. Select Image --> Adjust --> Brightness_Contrast, adjust to have signal similar to the example image on this page."),
                                h6("5. Select Image --> Scale --> Should be set to 50% (0.5) --> Select OK"),
                                h6("6. Select File --> Save as --> Tiff"),
                                h6("*Please note that high-quality images are needed for proper quantification (please see example below)."),
                                fluidRow(withSpinner(plotOutput("pdf_2"), type = 6), style = 'padding:4px;'),
                                br(),
                                h4("Image Analysis"),
                                h6("1. Upload tiff image file and wait for upload to complete."),
                                h6("2. Click the submit button to run the image analysis. Please allow a few minutes for image processing."),
                                h6("3. When finished, you may click the reset button to submit another image for analysis."),
                                h6("*Files may generally need ~1 minute of processing time."),
                                br(),
                                fluidRow(column(6, fileInput("file3", "Please upload an 8-bit Tiff Image"), actionButton("submit_3", "Submit"))),
                                fluidRow(h4("Original Image"), withSpinner(plotOutput("img_3"), type = 6), style = 'padding:4px;')),
                              fluidRow(h4("Interval Quantification"),column(3,h6("First Interval"),withSpinner(plotOutput("int_1_3"), type = 6), style = 'padding:4px;'), column(3,h6("Second Interval"), withSpinner(plotOutput("int_2_3"), type = 6), style = 'padding:4px;'), column(3,h6("Third Interval"), withSpinner(plotOutput("int_3_3"), type = 6), style = 'padding:4px;'), column(3,h6("Fourth Interval"), withSpinner(plotOutput("int_4_3"), type = 6), style = 'padding4px;'),
                                       h4("Mean MFI"),
                                       fluidRow(withSpinner(DTOutput("results_3"), type = 6), style = 'padding:4px;', actionButton("reset_3", "Reset"))
                              )),
                  #Normalized MFI Tab User Interface    
                  tabItem(tabName = 'SCG10_DAPI',
                              fluidPage(
                                h2("Normalized Mean Fluorescence Intensity (MFI) Quantification"),
                                br(),
                                h4("Image Pre-Processing Instructions"),
                                h6("1. Open FIJI Software, select File --> Open --> select image file."),
                                h6("2. To straighten & crop nerves from injury site to the distal nerve, do the following:"),
                                h6("   a. Select Edit --> Options --> Line Width, set equal to ~2,500"),
                                h6("      *For MFI quantification, it is important that this number is optimized to fit the nerve and reduce background image that may dilute the overall MFI quantification."),
                                h6("   b. Right-click line tile --> Select segmented line"),
                                h6("   c. Click at nerve crush site, and then click in the middle of the nerve until at distal nerve end, then right-click."),
                                h6("   d. Search for the straighten plugin and then run."),
                                h6("   *Make sure empty space is not present in the cropped image, or this will interfere with the MFI calculation."),
                                h6("3. Select Image --> Type --> 8-bit"),
                                h6("4. Select Image --> Adjust --> Brightness_Contrast, adjust to have signal similar to the example image on this page."),
                                h6("5. Select Image --> Scale --> Should be set to 50% (0.5) --> Select OK"),
                                h6("6. Select File --> Save as --> Tiff"),
                                h6("7. Record the pixel height in inches: Select Image --> Properties"),
                                h6("8. Repeat steps 1-5 with an image file of nuclear staining (i.e., DAPI)."),
                                h6("*Please note no nuclear staining can be on the edges of the cropped image or the code may fail to acquire the upper/lower limit of the nerve width."),
                                h6("*Please note that high-quality images are needed for proper quantification (please see example below)."),
                                h6("SCG10 Example"),
                                fluidRow(withSpinner(plotOutput("pdf_3"), type = 6), style = 'padding:4px;'),
                                h6("Hoechst Example"),
                                fluidRow(withSpinner(plotOutput("pdf_4"), type = 6), style = 'padding:4px;'),
                                br(),
                                h4("Image Analysis"),
                                h6("1. Upload tiff image file and wait for upload to complete."),
                                h6("2. Upload nuclear stained tiff image file and wait for upload to complete."),
                                h6("3. Input the height of pixels in inches for the image."),
                                h6("4. Click the submit button to run the image analysis. Please allow a few minutes for image processing."),
                                h6("5. When finished, you may click the reset button to submit another image for analysis."),
                                h6("*Files may generally need ~8 minutes of processing time."),
                                br(),
                                fluidRow(column(6, fileInput("file6", "Please upload an 8-bit Tiff image", multiple = TRUE))),
                                fluidRow(column(6, fileInput("file7", "Please upload an 8-bit Tiff image (nucelar staining)"))),
                                fluidRow(numericInput("mtpr_2", "Pixel Height (Inches)", value = 0, min = 0), actionButton("submit_5", "Submit")),
                                fluidRow(h4("Original Image"), column(6, h6("Stain of Interest"),withSpinner(plotOutput("img_6"), type = 6)), column(6,h6("Nuclear Stain"), withSpinner(plotOutput("img_7"),type = 6)), style = 'padding:4px;'),
                                fluidRow(h4("Interval Quantification"), column(3,h6("First Interval"), h6("Stain of Interest"), withSpinner(plotOutput("int_1_6"), type = 6), h6("Nuclear Stain"), withSpinner(plotOutput("int_1_7"), type = 6)), column(3,h6("Second Interval"),h6("Stain of Interest"),withSpinner(plotOutput("int_2_6"),type = 6), h6("Nuclear Stain"), withSpinner(plotOutput("int_2_7"), type = 6)), column(3,h6("Third Interval"),h6("Stain of Interest"),withSpinner(plotOutput("int_3_6"), type = 6), h6("Nuclear Stain"),withSpinner(plotOutput("int_3_7"), type = 6)), column(3,h6("Fourth Interval"), h6("Stain of Interest"),withSpinner(plotOutput("int_4_6"), type = 6), h6("Nuclear Stain"),withSpinner(plotOutput("int_4_7"), type = 6)), style = 'padding:4px;'),
                                h4("Mean MFI"),
                                fluidRow(withSpinner(DTOutput("results_5"), type = 6), style = 'padding:4px;', actionButton("reset_5", "Reset"))
                              )),
                  #Multiple Files MFI Tab User Interface    
                  tabItem(tabName = "multiple_mfi",
                              fluidPage(shinyjs::useShinyjs(),
                                        h2("Mean Fluorescence Intensity (MFI) Quantification for Multiple Files"),
                                        br(),
                                        h4("Image Pre-Processing Instructions (to do for each file)"),
                                        h6("1. Open FIJI Software, select File --> Open --> select image file."),
                                        h6("2. To straighten & crop nerves from injury site to the distal nerve, do the following:"),
                                        h6("   a. Select Edit --> Options --> Line Width, set equal to ~2,500"),
                                        h6("   b. Right-click line tile --> Select segmented line"),
                                        h6("   c. Click at nerve crush site, and then click in the middle of the nerve until at distal nerve end, then right-click."),
                                        h6("   d. Search for the straighten plugin and then run."),
                                        h6("   *Make sure empty space is not present in the cropped image, or this will interfere with the MFI calculation."),
                                        h6("3. Select Image --> Type --> 8-bit"),
                                        h6("4. Select Image --> Adjust --> Brightness_Contrast, adjust maximum value to give optimal signal."),
                                        h6("5. Select Image --> Scale --> Should be set to 50% (0.5) --> Select OK"),
                                        h6("6. Select File --> Save as --> Tiff"),
                                        h6("*Please note that high-quality images are needed for proper quantification (please see example below)."),
                                        fluidRow(withSpinner(plotOutput("pdf_33"), type = 6), style = 'padding:4px;'),
                                        br(),
                                        h4("Image Analysis"),
                                        h6("1. Upload your tiff image files (select multiple files at once, we recommend no more than 10 images at once) and wait for upload to complete. Do not upload a folder but just the files."),
                                        h6("2. Click the submit button to run the image analysis. Please allow a few minutes for image processing."),
                                        h6("*One file may generally take 1-2 minutes to process, so please be patient for all files to finish."),
                                        h6("*Please reset browser after quantifying set of images if doing more multiple file quantification."),
                                        br(), 
                                        fluidRow(column(6, fileInput("list_multiple_mfi", "Please upload your images", multiple = TRUE, accept = c(".tif", ".tiff", "image/tiff")), actionButton("submit_multiple_files_mfi", "Submit"))),
                                        h4("Mean MFI"),
                                        fluidRow(withSpinner(DTOutput("results_multiple_files_mfi"), type = 6), style = 'padding:4px;'),
                                        h6("*If submitting more than one job for batch processing, please upload the next batch of images to process once the original batch finishes and hit submit again.")
                                        )),
                  #Single File Rbpms Tab User Interface    
                  tabItem(tabName = 'Rbpms_Counting',
                              fluidPage(
                                h2("RGC Quantification"),
                                br(),
                                h4("Image Pre-Processing Instructions"),
                                h6("1. Open FIJI Software, select File --> Open --> select image file."),
                                h6("2. Select Image --> Type --> 8-bit"),
                                h6("3. Select Image --> Adjust --> Brightness_Contrast, adjust to have signal similar to the example image on this page."),
                                h6("4. Select Image --> Scale --> Should be set to 50% (0.5) --> Select OK"),
                                h6("5. Select File --> Save as --> Tiff"),
                                h6("*Please note that high-quality images are needed for proper quantification (please see example below)."),
                                fluidRow(withSpinner(plotOutput("pdf_1"), type = 6), style = 'padding:4px;'),
                                br(),
                                h4("Image Analysis"),
                                h6("1. Upload tiff image file and wait for upload to complete."),
                                h6("2. Click the submit button to run the image analysis. Please allow a few minutes for image processing."),
                                h6("3. When finished, you may click the reset button to submit another image for analysis."),
                                br(),
                                fluidRow(column(6, fileInput("file2", "Please upload an 8-bit Tiff Image"), actionButton("submit_2", "Submit"))),
                                fluidRow(h4("Original Image"), withSpinner(plotOutput("img_2"), type = 6), style = 'padding:4px;'),
                                fluidRow(h4("Masked Image"), withSpinner(plotOutput("mask_2"), type = 6), style = 'padding:4px;'),
                                fluidRow(h4("Object Image"), withSpinner(plotOutput("obj_2"), type = 6), style = 'padding:4px;'),
                                h4("Number of RGCs"),
                                fluidRow(withSpinner(DTOutput("results_2"), type = 6), style = 'padding:4px;', actionButton("reset_2", "Reset")))),
                  #Multiple File Rbpms Tab User Interface    
                  tabItem(tabName = 'Rbpms_multiple_files',
                              fluidPage(
                                h2("RGC Quantification for Multiple Files"),
                                br(),
                                h4("Image Pre-Processing Instructions (to do for each file)"),
                                h6("1. Open FIJI Software, select File --> Open --> select image file."),
                                h6("2. Select Image --> Type --> 8-bit"),
                                h6("3. Select Image --> Adjust --> Brightness_Contrast, adjust to have signal similar to the example image on this page."),
                                h6("4. Select Image --> Scale --> Should be set to 50% (0.5) --> Select OK"),
                                h6("5. Select File --> Save as --> Tiff"),
                                h6("*Please note that high-quality images are needed for proper quantification (please see example below)."),
                                fluidRow(withSpinner(plotOutput("pdf"), type = 6), style = 'padding:4px;'),
                                br(),
                                h4("Image Analysis"),
                                h6("1. Upload tiff image files (select multiple files at once) and wait for upload to complete."),
                                h6("2. Click the submit button to run the image analysis. Please allow a few minutes for image processing."),
                                h6("3. When finished, you may click the reset button to submit another image for analysis."),
                                br(),
                                fluidRow(column(6, fileInput("file_multiple_Rbpms", "Please upload 8-bit Tiff Images", multiple = TRUE, accept = c(".tif", ".tiff", "image/tiff")), actionButton("submit_multiple_Rbpms", "Submit"))),
                                h4("Number of RGCs"),
                                fluidRow(withSpinner(DTOutput("results_multiple_Rbpms"), type = 6), style = 'padding:4px;')
                              ))
                    )))
  return(ui)
}
